<a href="https://colab.research.google.com/github/kdemertzis/EKPA/blob/main/Diabetes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.neural_network import MLPClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

## ΑΛΛΑΓΗ ΣΥΝΟΛΟΥ ΔΕΔΟΜΕΝΩΝ
data = pd.read_csv('https://raw.githubusercontent.com/kdemertzis/EKPA/main/Data/phishing_dataset.csv', delimiter=',')

In [2]:
data = data.sample(frac=1).reset_index(drop=True)
data.head()

Domain  Have_IP  Have_At  URL_Length  URL_Depth  \
0       mikulaskocogas.hu        0        0           0          3   
1          megeofhedt.com        0        0           0          2   
2  cheaproomsvalencia.com        0        0           1          5   
3         arstechnica.com        0        0           1          4   
4              fishki.net        0        0           1          2   

   Redirection  https_Domain  TinyURL  Prefix/Suffix  DNS_Record  Web_Traffic  \
0            0             0        0              0           0            1   
1            0             0        1              0           0            1   
2            0             0        0              0           0            1   
3            0             0        0              0           0            1   
4            0             0        0              0           0            1   

   Domain_Age  Domain_End  iFrame  Mouse_Over  Right_Click  Web_Forwards  \
0           1           1       0           0            1             0   
1           1           1       0           0            1             0   
2           0           0       1           0            1             0   
3           1           1       0           0            1             0   
4           0           1       0           0            1             0   

   Label  
0      1  
1      1  
2      1  
3      0  
4      0

In [3]:
## ΑΦΑΙΡΕΣΗ ΣΤΗΛΩΝ
X = data.drop(['Domain', 'Label'], axis=1)

In [4]:
X.head()

Have_IP  Have_At  URL_Length  URL_Depth  Redirection  https_Domain  \
0        0        0           0          3            0             0   
1        0        0           0          2            0             0   
2        0        0           1          5            0             0   
3        0        0           1          4            0             0   
4        0        0           1          2            0             0   

   TinyURL  Prefix/Suffix  DNS_Record  Web_Traffic  Domain_Age  Domain_End  \
0        0              0           0            1           1           1   
1        1              0           0            1           1           1   
2        0              0           0            1           0           0   
3        0              0           0            1           1           1   
4        0              0           0            1           0           1   

   iFrame  Mouse_Over  Right_Click  Web_Forwards  
0       0           0            1             0  
1       0           0            1             0  
2       1           0            1             0  
3       0           0            1             0  
4       0           0            1             0

In [6]:
## ΕΠΙΛΟΓΗ ΣΤΗΛΗΣ
y=np.ravel(data['Label'])

In [7]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.3, random_state=43)

In [8]:
# Standardize the features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [9]:
# Define classifiers
classifiers = [
    LogisticRegression(),
    SVC(),
    RandomForestClassifier(),
    MLPClassifier(),
    KNeighborsClassifier(),
    DecisionTreeClassifier()
]

In [10]:
# Evaluate and compare classifiers
results = {'Classifier': [], 'Accuracy': [], 'Precision': [], 'Recall': [], 'F1 Score': []}

for clf in classifiers:
    clf_name = clf.__class__.__name__

    # Train the classifier
    clf.fit(X_train, y_train)

    # Make predictions
    y_pred = clf.predict(X_test)

    # Calculate evaluation metrics
    acc = accuracy_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred, average='weighted')
    recall = recall_score(y_test, y_pred, average='weighted')
    f1 = f1_score(y_test, y_pred, average='weighted')

    # Confusion matrix
    cm = confusion_matrix(y_test, y_pred)

    # Display results
    print(f"\n{clf_name} Metrics:")
    print(f"Accuracy: {acc}")
    print(f"Precision: {precision}")
    print(f"Recall: {recall}")
    print(f"F1 Score: {f1}")
    print("Confusion Matrix:")
    print(cm)

    # Store results for comparison
    results['Classifier'].append(clf_name)
    results['Accuracy'].append(acc)
    results['Precision'].append(precision)
    results['Recall'].append(recall)
    results['F1 Score'].append(f1)


LogisticRegression Metrics:
Accuracy: 0.8033333333333333
Precision: 0.8300405501628796
Recall: 0.8033333333333333
F1 Score: 0.7991277252906976
Confusion Matrix:
[[1425   81]
 [ 509  985]]

SVC Metrics:
Accuracy: 0.8283333333333334
Precision: 0.8658268428894429
Recall: 0.8283333333333334
F1 Score: 0.8236847025865509
Confusion Matrix:
[[1489   17]
 [ 498  996]]

RandomForestClassifier Metrics:
Accuracy: 0.8596666666666667
Precision: 0.8696094933602198
Recall: 0.8596666666666667
F1 Score: 0.8586616710618332
Confusion Matrix:
[[1419   87]
 [ 334 1160]]


/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(



MLPClassifier Metrics:
Accuracy: 0.8516666666666667
Precision: 0.8693354773070132
Recall: 0.8516666666666667
F1 Score: 0.8497934232273667
Confusion Matrix:
[[1448   58]
 [ 387 1107]]

KNeighborsClassifier Metrics:
Accuracy: 0.8456666666666667
Precision: 0.8497329856908067
Recall: 0.8456666666666667
F1 Score: 0.8451758455856734
Confusion Matrix:
[[1356  150]
 [ 313 1181]]

DecisionTreeClassifier Metrics:
Accuracy: 0.8543333333333333
Precision: 0.8697268124855079
Recall: 0.8543333333333333
F1 Score: 0.85273014267205
Confusion Matrix:
[[1441   65]
 [ 372 1122]]


In [11]:
# Display comparison results
results_df = pd.DataFrame(results)
results_df = results_df.sort_values(by='Accuracy', ascending=False)
print("\nComparison of Classifiers:")
print(results_df)


Comparison of Classifiers:
               Classifier  Accuracy  Precision    Recall  F1 Score
2  RandomForestClassifier  0.859667   0.869609  0.859667  0.858662
5  DecisionTreeClassifier  0.854333   0.869727  0.854333  0.852730
3           MLPClassifier  0.851667   0.869335  0.851667  0.849793
4    KNeighborsClassifier  0.845667   0.849733  0.845667  0.845176
1                     SVC  0.828333   0.865827  0.828333  0.823685
0      LogisticRegression  0.803333   0.830041  0.803333  0.799128
